spring:
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://118.178.136.160:3306/blog?useUnicode=true&characterEncoding=utf-8&serverTimezone=UTC
    username: root
    password: jiajia123
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true

logging:
  level:
    root: info
    com.lrm: debug

  file:
    name: log/myBlog-dev.log
server:
  port: 443
  ssl:
    key-store: classpath:4413549_www.jiangsijia.cn.pfx
    key-store-password: 4JDm29uR
    key-store-type: PKCS12
    enabled: true